/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <DAC_out.h>
#include <DAC_out_aliases.h>
#include <ADC_DelSig_1.h>
#include <DMA_1_dma.h>
#include <VDAC8_1.h>
#include <isr_2.h>
#include <Filter_1.h>
#include <Filter_1_PVT.h>
#include <DMA_2_dma.h>
#include <Control_Reg_1.h>
#include <isr_1.h>
#include <Signal_in.h>
#include <Signal_in_aliases.h>
#include <PWM_1.h>
#include <Opamp_1.h>
#include <V_Ref.h>
#include <V_Ref_aliases.h>
#include <PGA_1.h>
#include <IRQ_Zigbee.h>
#include <IRQ_Zigbee_aliases.h>
#include <Clock_2.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <isr_Receive_Data.h>
#include <nRESET.h>
#include <nRESET_aliases.h>
#include <WAKE.h>
#include <WAKE_aliases.h>
#include <CS.h>
#include <CS_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <Mobile_motor.h>
#include <Mobile_motor_aliases.h>
#include <Cradle_motor.h>
#include <Cradle_motor_aliases.h>
#include <Clock_1.h>
#include <AMux_1.h>
#include <Temp_in.h>
#include <Temp_in_aliases.h>
#include <SPI.h>
#include <SPI_PVT.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_IRQ.h>
#include <ADC_DelSig_1_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

